### ISSUE TITLE
macOS 10.14 (Mojave) Compatibility?

### ISSUE THREAD

**Issue by Fofer** [w0lfschild/iMessageParity#1]
Hi, I loved this SIMBL add-on in macOS 10.13 (High Sierra) but it's not working for me in 10.14.  My other add-ons (CleanHUD, cDock, NotificationClear, etc.) are working fine on my system, and SIP is disabled.  Is iMessageParity compatible with Mojave?

**Comment by w0lfschild** [comment]
I'll look into this. Seems like it is indeed not loading / broken.

**Comment by w0lfschild** [comment]
Try using [MacForge](https://github.com/w0lfschild/MacForge) to load it instead.
